name: Linters

on: pull_request

jobs:
  prettier:
    name: Prettier Checking
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v4
      - uses: actions/setup-node@v4
        with:
          node-version: '22.11.0'
      - uses: pnpm/action-setup@v4
        with:
          version: 9
      - run: pnpm i
      - run: pnpm run lint:prettier:check

  eslint:
    name: Eslint Checking
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v4
      - uses: actions/setup-node@v4
        with:
          node-version: '22.11.0'
      - uses: pnpm/action-setup@v4
        with:
          version: 9
      - run: pnpm i
      - run: pnpm run lint:eslint:check

  commitlint:
    name: Commitlint Checking
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v4
        with:
          fetch-depth: 0
      - uses: actions/setup-node@v4
        with:
          node-version: '22.11.0'
      - uses: pnpm/action-setup@v4
        with:
          version: 9
      - run: pnpm i
      - run: pnpx commitlint --from ${{ github.event.pull_request.head.sha }}~${{ github.event.pull_request.commits }} --to ${{ github.event.pull_request.head.sha }} --verbose
